version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./database/migration.sql:/docker-entrypoint-initdb.d/migration.sql

  next:
    build: ./
    restart: always
    ports:
      - 3000:3000
    environment:
      - BASE_URL=http://localhost:3000/interview
      - CONNECTION_STRING=postgresql://postgres:docker@database:5432/database
    depends_on:
      - database
